#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# {
#     'tcp_port': 8443,
#     'secret': 'wef',
#     'user': 'wefwef'
# }


def agent_cisco_ucm_arguments(params, hostname, ipaddress):
    args = []
    if "tcp_port" in params:
        args += ["-p", "%d" % params["tcp_port"]]

    args += ["-u", params["user"]]
    args += ["-s", passwordstore_get_cmdline("%s", params["secret"])]

    if "timeout" in params:
        args += ['--timeout', params["timeout"]]

    if "ssl" in params:
        if params["ssl"] is False:
            args += ['--no-cert-check', ipaddress]
        elif params["ssl"] is True:
            args.append(hostname)
        else:
            args.append(params["ssl"])
    else:  # legacy mode
        args.append(ipaddress)

    return args


special_agent_info['cisco_ucm'] = agent_cisco_ucm_arguments
